apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:lts-community
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "3Gi"
            cpu: "3"
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 31000
  selector:
    app: sonarqube
  type: NodePort
